-- 招生 OCR 结构化数据表
-- 本 SQL 只创建 MySQL 结构化表，不写入 kb_content，也不接入 Redis Vector。

CREATE TABLE IF NOT EXISTS `admission_ocr_batch` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `batch_no` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'OCR批次号',
  `source_type` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT 'IMAGE_DIR' COMMENT '来源类型：IMAGE_DIR/IMAGE_FILE/MANUAL_IMPORT等',
  `source_path` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '来源路径',
  `file_count` int NULL DEFAULT 0 COMMENT '图片文件数量',
  `total_records` int NULL DEFAULT 0 COMMENT '记录总数',
  `valid_records` int NULL DEFAULT 0 COMMENT '有效记录数',
  `invalid_records` int NULL DEFAULT 0 COMMENT '问题记录数',
  `status` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'PENDING' COMMENT '状态：PENDING/IMPORTED/FAILED',
  `remark` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '备注',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uk_admission_ocr_batch_no` (`batch_no`) USING BTREE,
  KEY `idx_admission_ocr_batch_status` (`status`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='招生OCR批处理任务表' ROW_FORMAT=DYNAMIC;

CREATE TABLE IF NOT EXISTS `admission_major_record` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `batch_id` bigint NULL DEFAULT NULL COMMENT 'OCR批次ID',
  `batch_no` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'OCR批次号',
  `school_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '学校名称',
  `school_code` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '学校代码',
  `college_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '学院名称',
  `major_code` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '专业代码',
  `major_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '专业名称',
  `research_direction` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '研究方向',
  `exam_subjects` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '初试科目',
  `score_line` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '分数线',
  `retest_count` int NULL DEFAULT NULL COMMENT '复试人数',
  `admitted_count` int NULL DEFAULT NULL COMMENT '录取人数',
  `avg_score` decimal(6,2) NULL DEFAULT NULL COMMENT '平均分',
  `min_score` decimal(6,2) NULL DEFAULT NULL COMMENT '最低分',
  `max_score` decimal(6,2) NULL DEFAULT NULL COMMENT '最高分',
  `year` int NULL DEFAULT NULL COMMENT '招生年份',
  `source_image` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '来源图片',
  `file_hash` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '来源图片SHA-256',
  `confidence` decimal(5,4) NULL DEFAULT NULL COMMENT 'OCR记录置信度，0到1',
  `issues` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '质量问题JSON字符串',
  `review_status` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'PENDING' COMMENT '审核状态：PENDING/APPROVED/REJECTED',
  `review_comment` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '审核备注',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_admission_major_batch_id` (`batch_id`) USING BTREE,
  KEY `idx_admission_major_batch_no` (`batch_no`) USING BTREE,
  KEY `idx_admission_major_school` (`school_code`, `school_name`) USING BTREE,
  KEY `idx_admission_major_major` (`major_code`, `major_name`) USING BTREE,
  KEY `idx_admission_major_review` (`review_status`) USING BTREE,
  KEY `idx_admission_major_file_hash` (`file_hash`) USING BTREE,
  CONSTRAINT `fk_admission_major_batch` FOREIGN KEY (`batch_id`) REFERENCES `admission_ocr_batch` (`id`) ON DELETE SET NULL ON UPDATE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='招生OCR专业结构化记录表' ROW_FORMAT=DYNAMIC;
