server:
  port: 9090

spring:
  profiles:
    active: local
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB

  datasource:
    driver-class-name: ${lhz.spring.datasource.driver-class-name}
    username: ${lhz.spring.datasource.username}
    password: ${lhz.spring.datasource.password}
    url: ${lhz.spring.datasource.url}

  data:
    redis:
      host: ${lhz.spring.data.redis.host}
      port: ${lhz.spring.data.redis.port}

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml

fileBaseUrl: ${lhz.fileBaseUrl}

langchain4j:
  open-ai:
    chat-model:
      base-url: ${lhz.langchain4j.open-ai.chat-model.base-url}
      api-key: ${lhz.langchain4j.open-ai.chat-model.api-key}
      model-name: ${lhz.langchain4j.open-ai.chat-model.model-name}
      log-requests: true
      log-responses: true

    streaming-chat-model:
      base-url: ${lhz.langchain4j.open-ai.streaming-chat-model.base-url}
      api-key: ${lhz.langchain4j.open-ai.streaming-chat-model.api-key}
      model-name: ${lhz.langchain4j.open-ai.streaming-chat-model.model-name}
      log-requests: true
      log-responses: true

    embedding-model:
      base-url: ${lhz.langchain4j.open-ai.embedding-model.base-url}
      api-key: ${lhz.langchain4j.open-ai.embedding-model.api-key}
      model-name: ${lhz.langchain4j.open-ai.embedding-model.model-name}
      log-requests: true
      log-responses: true
      max-segments-per-batch: 10

  community:
    redis:
      host: ${lhz.langchain4j.community.redis.host}
      port: ${lhz.langchain4j.community.redis.port}
      dimension: 1024

app:
  chat:
    memory:
      ttl-days: 7
  knowledge-base:
    upload-dir: ${lhz.app.knowledge-base.upload-dir}
